
version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: postgres-db
    environment:
      POSTGRES_USER: vladislavobedkov
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: test3
    ports:
      - "5433:5432"

  server:
    build:
      context: ./server
    container_name: nestjs-server
    ports:
      - "4200:4200"
    depends_on:
      - db
    environment:
      DB_USER: vladislavobedkov
      DB_HOST: db
      DB_NAME: test3
      DB_PASSWORD: yourpassword
      DB_PORT: 5432

  client:
    build:
      context: ./client
    container_name: static-client
    ports:
      - "80:80"
