version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: vladislavobedkov
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: java-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/test
      DB_USER: vladislavobedkov
      DB_PASSWORD: yourpassword
    networks:
      - mynetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: static-client
    ports:
      - "8081:80"  # Измените на нужный вам порт
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
